@startuml
User -> (logar na rede social)
User --> (editar conta)
User ---> (adicionar amigo)
User ----> (remover amigo)
User -----> (enviar menssagem privada)
User ------> (enviar menssagem publica)
User -------> (publicar apenas para amigo)
User --------> (publicar para qualquer membro da rede)
User ---------> (definir tipo de post)
User ----------> (realizar busca especifica)
User -----------> (realizar busca geral)
User ----------> (mostrar menssagem privada)
User ---------> (mostrar menssagem publica)
User --------> (realizar busca de amigo por nome)
User -------> (editar perfil)
User ------> (reagir a publicação)
User -----> (comentar publicação)
User ----> (compartilhar publicação)
User ---> (editar grupo)
User --> (editar pagina)
User -> (acessar notificação)
@enduml
